// Code generated by "stringer -type=ActiveConnectionStateReason"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActiveConnectionStateReasonUnknown-0]
	_ = x[ActiveConnectionStateReasonNone-1]
	_ = x[ActiveConnectionStateReasonUserDisconnected-2]
	_ = x[ActiveConnectionStateReasonDeviceDisconnected-3]
	_ = x[ActiveConnectionStateReasonServiceStopped-4]
	_ = x[ActiveConnectionStateReasonIPConfigInvalid-5]
	_ = x[ActiveConnectionStateReasonConnectTimeout-6]
	_ = x[ActiveConnectionStateReasonServiceStartTimeout-7]
	_ = x[ActiveConnectionStateReasonServiceStartFailed-8]
	_ = x[ActiveConnectionStateReasonNoSecrets-9]
	_ = x[ActiveConnectionStateReasonLoginFailed-10]
	_ = x[ActiveConnectionStateReasonConnectionRemoved-11]
	_ = x[ActiveConnectionStateReasonDependencyFailed-12]
	_ = x[ActiveConnectionStateReasonDeviceRealizeFailed-13]
	_ = x[ActiveConnectionStateReasonDeviceRemoved-14]
}

const _ActiveConnectionStateReason_name = "ActiveConnectionStateReasonUnknownActiveConnectionStateReasonNoneActiveConnectionStateReasonUserDisconnectedActiveConnectionStateReasonDeviceDisconnectedActiveConnectionStateReasonServiceStoppedActiveConnectionStateReasonIPConfigInvalidActiveConnectionStateReasonConnectTimeoutActiveConnectionStateReasonServiceStartTimeoutActiveConnectionStateReasonServiceStartFailedActiveConnectionStateReasonNoSecretsActiveConnectionStateReasonLoginFailedActiveConnectionStateReasonConnectionRemovedActiveConnectionStateReasonDependencyFailedActiveConnectionStateReasonDeviceRealizeFailedActiveConnectionStateReasonDeviceRemoved"

var _ActiveConnectionStateReason_index = [...]uint16{0, 34, 65, 108, 153, 194, 236, 277, 323, 368, 404, 442, 486, 529, 575, 615}

func (i ActiveConnectionStateReason) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ActiveConnectionStateReason_index)-1 {
		return "ActiveConnectionStateReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActiveConnectionStateReason_name[_ActiveConnectionStateReason_index[idx]:_ActiveConnectionStateReason_index[idx+1]]
}
