// Code generated by "stringer -type=ActiveConnectionState"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActiveConnectionStateUnknown-0]
	_ = x[ActiveConnectionStateActivating-1]
	_ = x[ActiveConnectionStateActivated-2]
	_ = x[ActiveConnectionStateDeactivating-3]
	_ = x[ActiveConnectionStateDeactivated-4]
}

const _ActiveConnectionState_name = "ActiveConnectionStateUnknownActiveConnectionStateActivatingActiveConnectionStateActivatedActiveConnectionStateDeactivatingActiveConnectionStateDeactivated"

var _ActiveConnectionState_index = [...]uint8{0, 28, 59, 89, 122, 154}

func (i ActiveConnectionState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ActiveConnectionState_index)-1 {
		return "ActiveConnectionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActiveConnectionState_name[_ActiveConnectionState_index[idx]:_ActiveConnectionState_index[idx+1]]
}
