// Code generated by "stringer -type=ActivationStateFlag"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActivationStateFlagNone-0]
	_ = x[ActivationStateFlagIsMaster-1]
	_ = x[ActivationStateFlagIsSlave-2]
	_ = x[ActivationStateFlagLayer2Ready-4]
	_ = x[ActivationStateFlagIP4Ready-8]
	_ = x[ActivationStateFlagIP6Ready-16]
	_ = x[ActivationStateFlagMasterHasSlaves-32]
	_ = x[ActivationStateFlagLifetimeBoundToProfileVisibility-64]
}

const (
	_ActivationStateFlag_name_0 = "ActivationStateFlagNoneActivationStateFlagIsMasterActivationStateFlagIsSlave"
	_ActivationStateFlag_name_1 = "ActivationStateFlagLayer2Ready"
	_ActivationStateFlag_name_2 = "ActivationStateFlagIP4Ready"
	_ActivationStateFlag_name_3 = "ActivationStateFlagIP6Ready"
	_ActivationStateFlag_name_4 = "ActivationStateFlagMasterHasSlaves"
	_ActivationStateFlag_name_5 = "ActivationStateFlagLifetimeBoundToProfileVisibility"
)

var (
	_ActivationStateFlag_index_0 = [...]uint8{0, 23, 50, 76}
)

func (i ActivationStateFlag) String() string {
	switch {
	case i <= 2:
		return _ActivationStateFlag_name_0[_ActivationStateFlag_index_0[i]:_ActivationStateFlag_index_0[i+1]]
	case i == 4:
		return _ActivationStateFlag_name_1
	case i == 8:
		return _ActivationStateFlag_name_2
	case i == 16:
		return _ActivationStateFlag_name_3
	case i == 32:
		return _ActivationStateFlag_name_4
	case i == 64:
		return _ActivationStateFlag_name_5
	default:
		return "ActivationStateFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
