// Code generated by "stringer -type=APFlags"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APFlagsNone-0]
	_ = x[APFlagsPrivacy-1]
}

const _APFlags_name = "APFlagsNoneAPFlagsPrivacy"

var _APFlags_index = [...]uint8{0, 11, 25}

func (i APFlags) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_APFlags_index)-1 {
		return "APFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _APFlags_name[_APFlags_index[idx]:_APFlags_index[idx+1]]
}
