// Code generated by "stringer -type=APSecurity"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APSecurityNone-0]
	_ = x[APSecurityPairWEP40-1]
	_ = x[APSecurityPairWEP104-2]
	_ = x[APSecurityPairTKIP-4]
	_ = x[APSecurityPairCCMP-8]
	_ = x[APSecurityGroupWEP40-16]
	_ = x[APSecurityGroupWEP104-32]
	_ = x[APSecurityGroupTKIP-64]
	_ = x[APSecurityGroupCCMP-128]
	_ = x[APSecurityKeyMgmtPSK-256]
	_ = x[APSecurityKeyMgmt8021X-512]
	_ = x[APSecurityKeyMgmtSAE-1024]
	_ = x[APSecurityKeyMgmtOWE-2048]
	_ = x[APSecurityKeyMgmtOWETM-4096]
}

const _APSecurity_name = "APSecurityNoneAPSecurityPairWEP40APSecurityPairWEP104APSecurityPairTKIPAPSecurityPairCCMPAPSecurityGroupWEP40APSecurityGroupWEP104APSecurityGroupTKIPAPSecurityGroupCCMPAPSecurityKeyMgmtPSKAPSecurityKeyMgmt8021XAPSecurityKeyMgmtSAEAPSecurityKeyMgmtOWEAPSecurityKeyMgmtOWETM"

var _APSecurity_map = map[APSecurity]string{
	0:    _APSecurity_name[0:14],
	1:    _APSecurity_name[14:33],
	2:    _APSecurity_name[33:53],
	4:    _APSecurity_name[53:71],
	8:    _APSecurity_name[71:89],
	16:   _APSecurity_name[89:109],
	32:   _APSecurity_name[109:130],
	64:   _APSecurity_name[130:149],
	128:  _APSecurity_name[149:168],
	256:  _APSecurity_name[168:188],
	512:  _APSecurity_name[188:210],
	1024: _APSecurity_name[210:230],
	2048: _APSecurity_name[230:250],
	4096: _APSecurity_name[250:272],
}

func (i APSecurity) String() string {
	if str, ok := _APSecurity_map[i]; ok {
		return str
	}
	return "APSecurity(" + strconv.FormatInt(int64(i), 10) + ")"
}
