// Code generated by "stringer -type=Capability"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CapabilityTeam-1]
}

const _Capability_name = "CapabilityTeam"

var _Capability_index = [...]uint8{0, 14}

func (i Capability) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Capability_index)-1 {
		return "Capability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Capability_name[_Capability_index[idx]:_Capability_index[idx+1]]
}
