// Code generated by "stringer -type=CheckpointCreateFlags"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CheckpointCreateFlagsNone-0]
	_ = x[CheckpointCreateFlagsDestroyAll-1]
	_ = x[CheckpointCreateFlagsDeleteNewConnections-2]
	_ = x[CheckpointCreateFlagsDisconnectNewDevices-4]
	_ = x[CheckpointCreateFlagsAllowOverlapping-8]
}

const (
	_CheckpointCreateFlags_name_0 = "CheckpointCreateFlagsNoneCheckpointCreateFlagsDestroyAllCheckpointCreateFlagsDeleteNewConnections"
	_CheckpointCreateFlags_name_1 = "CheckpointCreateFlagsDisconnectNewDevices"
	_CheckpointCreateFlags_name_2 = "CheckpointCreateFlagsAllowOverlapping"
)

var (
	_CheckpointCreateFlags_index_0 = [...]uint8{0, 25, 56, 97}
)

func (i CheckpointCreateFlags) String() string {
	switch {
	case i <= 2:
		return _CheckpointCreateFlags_name_0[_CheckpointCreateFlags_index_0[i]:_CheckpointCreateFlags_index_0[i+1]]
	case i == 4:
		return _CheckpointCreateFlags_name_1
	case i == 8:
		return _CheckpointCreateFlags_name_2
	default:
		return "CheckpointCreateFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
