// Code generated by "stringer -type=Connectivity"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnectivityUnknown-0]
	_ = x[ConnectivityNone-1]
	_ = x[ConnectivityPortal-2]
	_ = x[ConnectivityLimited-3]
	_ = x[ConnectivityFull-4]
}

const _Connectivity_name = "ConnectivityUnknownConnectivityNoneConnectivityPortalConnectivityLimitedConnectivityFull"

var _Connectivity_index = [...]uint8{0, 19, 35, 53, 72, 88}

func (i Connectivity) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Connectivity_index)-1 {
		return "Connectivity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Connectivity_name[_Connectivity_index[idx]:_Connectivity_index[idx+1]]
}
