// Code generated by "stringer -type=DeviceType"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeviceTypeUnknown-0]
	_ = x[DeviceTypeEthernet-1]
	_ = x[DeviceTypeWifi-2]
	_ = x[DeviceTypeUnused1-3]
	_ = x[DeviceTypeUnused2-4]
	_ = x[DeviceTypeBt-5]
	_ = x[DeviceTypeOlpcMesh-6]
	_ = x[DeviceTypeWimax-7]
	_ = x[DeviceTypeModem-8]
	_ = x[DeviceTypeInfiniband-9]
	_ = x[DeviceTypeBond-10]
	_ = x[DeviceTypeVlan-11]
	_ = x[DeviceTypeAdsl-12]
	_ = x[DeviceTypeBridge-13]
	_ = x[DeviceTypeGeneric-14]
	_ = x[DeviceTypeTeam-15]
	_ = x[DeviceTypeTun-16]
	_ = x[DeviceTypeIPTunnel-17]
	_ = x[DeviceTypeMacvlan-18]
	_ = x[DeviceTypeVxlan-19]
	_ = x[DeviceTypeVeth-20]
	_ = x[DeviceTypeMacsec-21]
	_ = x[DeviceTypeDummy-22]
	_ = x[DeviceTypePpp-23]
	_ = x[DeviceTypeOvsInterface-24]
	_ = x[DeviceTypeOvsPort-25]
	_ = x[DeviceTypeOvsBridge-26]
	_ = x[DeviceTypeWpan-27]
	_ = x[DeviceType6lowpan-28]
	_ = x[DeviceTypeWireguard-29]
	_ = x[DeviceTypeWifiP2p-30]
}

const _DeviceType_name = "DeviceTypeUnknownDeviceTypeEthernetDeviceTypeWifiDeviceTypeUnused1DeviceTypeUnused2DeviceTypeBtDeviceTypeOlpcMeshDeviceTypeWimaxDeviceTypeModemDeviceTypeInfinibandDeviceTypeBondDeviceTypeVlanDeviceTypeAdslDeviceTypeBridgeDeviceTypeGenericDeviceTypeTeamDeviceTypeTunDeviceTypeIPTunnelDeviceTypeMacvlanDeviceTypeVxlanDeviceTypeVethDeviceTypeMacsecDeviceTypeDummyDeviceTypePppDeviceTypeOvsInterfaceDeviceTypeOvsPortDeviceTypeOvsBridgeDeviceTypeWpanDeviceType6lowpanDeviceTypeWireguardDeviceTypeWifiP2p"

var _DeviceType_index = [...]uint16{0, 17, 35, 49, 66, 83, 95, 113, 128, 143, 163, 177, 191, 205, 221, 238, 252, 265, 283, 300, 315, 329, 345, 360, 373, 395, 412, 431, 445, 462, 481, 498}

func (i DeviceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DeviceType_index)-1 {
		return "DeviceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceType_name[_DeviceType_index[idx]:_DeviceType_index[idx+1]]
}
