// Code generated by "stringer -type=DeviceState"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeviceStateUnknown-0]
	_ = x[DeviceStateUnmanaged-10]
	_ = x[DeviceStateUnavailable-20]
	_ = x[DeviceStateDisconnected-30]
	_ = x[DeviceStatePrepare-40]
	_ = x[DeviceStateConfig-50]
	_ = x[DeviceStateNeedAuth-60]
	_ = x[DeviceStateIPConfig-70]
	_ = x[DeviceStateIPCheck-80]
	_ = x[DeviceStateSecondaries-90]
	_ = x[DeviceStateActivated-100]
	_ = x[DeviceStateDeactivating-110]
	_ = x[DeviceStateFailed-120]
}

const _DeviceState_name = "DeviceStateUnknownDeviceStateUnmanagedDeviceStateUnavailableDeviceStateDisconnectedDeviceStatePrepareDeviceStateConfigDeviceStateNeedAuthDeviceStateIPConfigDeviceStateIPCheckDeviceStateSecondariesDeviceStateActivatedDeviceStateDeactivatingDeviceStateFailed"

var _DeviceState_map = map[DeviceState]string{
	0:   _DeviceState_name[0:18],
	10:  _DeviceState_name[18:38],
	20:  _DeviceState_name[38:60],
	30:  _DeviceState_name[60:83],
	40:  _DeviceState_name[83:101],
	50:  _DeviceState_name[101:118],
	60:  _DeviceState_name[118:137],
	70:  _DeviceState_name[137:156],
	80:  _DeviceState_name[156:174],
	90:  _DeviceState_name[174:196],
	100: _DeviceState_name[196:216],
	110: _DeviceState_name[216:239],
	120: _DeviceState_name[239:256],
}

func (i DeviceState) String() string {
	if str, ok := _DeviceState_map[i]; ok {
		return str
	}
	return "DeviceState(" + strconv.FormatInt(int64(i), 10) + ")"
}
