// Code generated by "stringer -type=DeviceInterfaceFlags"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeviceInterfaceFlagsNone-0]
	_ = x[DeviceInterfaceFlagsUp-1]
	_ = x[DeviceInterfaceFlagsLowerUp-2]
	_ = x[DeviceInterfaceFlagsPromisc-4]
	_ = x[DeviceInterfaceFlagsCarrier-65536]
	_ = x[DeviceInterfaceFlagsLldpClientEnabled-131072]
}

const (
	_DeviceInterfaceFlags_name_0 = "DeviceInterfaceFlagsNoneDeviceInterfaceFlagsUpDeviceInterfaceFlagsLowerUp"
	_DeviceInterfaceFlags_name_1 = "DeviceInterfaceFlagsPromisc"
	_DeviceInterfaceFlags_name_2 = "DeviceInterfaceFlagsCarrier"
	_DeviceInterfaceFlags_name_3 = "DeviceInterfaceFlagsLldpClientEnabled"
)

var (
	_DeviceInterfaceFlags_index_0 = [...]uint8{0, 24, 46, 73}
)

func (i DeviceInterfaceFlags) String() string {
	switch {
	case i <= 2:
		return _DeviceInterfaceFlags_name_0[_DeviceInterfaceFlags_index_0[i]:_DeviceInterfaceFlags_index_0[i+1]]
	case i == 4:
		return _DeviceInterfaceFlags_name_1
	case i == 65536:
		return _DeviceInterfaceFlags_name_2
	case i == 131072:
		return _DeviceInterfaceFlags_name_3
	default:
		return "DeviceInterfaceFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
