// Code generated by "stringer -type=Metered"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MeteredUnknown-0]
	_ = x[MeteredYes-1]
	_ = x[MeteredNo-2]
	_ = x[MeteredGuessYes-3]
	_ = x[MeteredGuessNo-4]
}

const _Metered_name = "MeteredUnknownMeteredYesMeteredNoMeteredGuessYesMeteredGuessNo"

var _Metered_index = [...]uint8{0, 14, 24, 33, 48, 62}

func (i Metered) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Metered_index)-1 {
		return "Metered(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Metered_name[_Metered_index[idx]:_Metered_index[idx+1]]
}
