// Code generated by "stringer -type=RollbackResult"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RollbackResultOk-0]
	_ = x[RollbackResultErrNoDevice-1]
	_ = x[RollbackResultErrDeviceUnmanaged-2]
	_ = x[RollbackResultErrFailed-3]
}

const _RollbackResult_name = "RollbackResultOkRollbackResultErrNoDeviceRollbackResultErrDeviceUnmanagedRollbackResultErrFailed"

var _RollbackResult_index = [...]uint8{0, 16, 41, 73, 96}

func (i RollbackResult) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RollbackResult_index)-1 {
		return "RollbackResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RollbackResult_name[_RollbackResult_index[idx]:_RollbackResult_index[idx+1]]
}
