// Code generated by "stringer -type=State"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateUnknown-0]
	_ = x[StateAsleep-10]
	_ = x[StateDisconnected-20]
	_ = x[StateDisconnecting-30]
	_ = x[StateConnecting-40]
	_ = x[StateConnectedLocal-50]
	_ = x[StateConnectedSite-60]
	_ = x[StateConnectedGlobal-70]
}

const (
	_State_name_0 = "StateUnknown"
	_State_name_1 = "StateAsleep"
	_State_name_2 = "StateDisconnected"
	_State_name_3 = "StateDisconnecting"
	_State_name_4 = "StateConnecting"
	_State_name_5 = "StateConnectedLocal"
	_State_name_6 = "StateConnectedSite"
	_State_name_7 = "StateConnectedGlobal"
)

func (i State) String() string {
	switch {
	case i == 0:
		return _State_name_0
	case i == 10:
		return _State_name_1
	case i == 20:
		return _State_name_2
	case i == 30:
		return _State_name_3
	case i == 40:
		return _State_name_4
	case i == 50:
		return _State_name_5
	case i == 60:
		return _State_name_6
	case i == 70:
		return _State_name_7
	default:
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
