// Code generated by "stringer -type=VpnConnectionState"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VpnConnectionUnknown-0]
	_ = x[VpnConnectionPrepare-1]
	_ = x[VpnConnectionNeedAuth-2]
	_ = x[VpnConnectionConnect-3]
	_ = x[VpnConnectionIPConfigGet-4]
	_ = x[VpnConnectionActivated-5]
	_ = x[VpnConnectionFailed-6]
	_ = x[VpnConnectionDisconnected-7]
}

const _VpnConnectionState_name = "VpnConnectionUnknownVpnConnectionPrepareVpnConnectionNeedAuthVpnConnectionConnectVpnConnectionIPConfigGetVpnConnectionActivatedVpnConnectionFailedVpnConnectionDisconnected"

var _VpnConnectionState_index = [...]uint8{0, 20, 40, 61, 81, 105, 127, 146, 171}

func (i VpnConnectionState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_VpnConnectionState_index)-1 {
		return "VpnConnectionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VpnConnectionState_name[_VpnConnectionState_index[idx]:_VpnConnectionState_index[idx+1]]
}
