// Code generated by "stringer -type=WifiMode"; DO NOT EDIT.

package nmtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WifiModeUnknown-0]
	_ = x[WifiModeAdhoc-1]
	_ = x[WifiModeInfra-2]
	_ = x[WifiModeAP-3]
}

const _WifiMode_name = "WifiModeUnknownWifiModeAdhocWifiModeInfraWifiModeAP"

var _WifiMode_index = [...]uint8{0, 15, 28, 41, 51}

func (i WifiMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_WifiMode_index)-1 {
		return "WifiMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WifiMode_name[_WifiMode_index[idx]:_WifiMode_index[idx+1]]
}
